name: Verify package builds
on:
  push:
    branches:
      - "master"
  pull_request:
jobs:
  example-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Build
        run: |
          git clone --depth 1 https://github.com/os-js/osjs-example-application.git test
          cd test
          npm install
          npm install --install-links $GITHUB_WORKSPACE
          npm run build
  example-iframe-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Build
        run: |
          git clone --depth 1 https://github.com/os-js/osjs-example-iframe-application.git test
          cd test
          npm install
          npm install --install-links $GITHUB_WORKSPACE
          npm run build
  distro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Build
        run: |
          git clone --depth 1 https://github.com/os-js/OS.js.git test
          cd test
          npm install
          npm install --install-links $GITHUB_WORKSPACE
          npm run build
